### ISSUE TITLE
Text magnifier showing view underneath presented MZFormSheet

### ISSUE THREAD

**Issue by adomanico** [m1entus/MZFormSheetController#116]
We have a welcome screen presenting a mzformsheet with another login mzformsheet presented on top of that. The problem is when we use the text magnifier for selection it is showing the view underneath not the text. 

See the image for clarity: http://i.imgur.com/cefeclA.png

Any help is appreciated. 

Thanks,
Adrian

**Comment by m1entus** [comment]
I rewritten MZFormSheetController to MZFormSheetPresentationController which is build on iOS8+ and don't use UIWindow tricks. I am sure that you will not have problem if you use it
