### ISSUE TITLE
Bluured background image incorrect after rotation on iPhone 6

### ISSUE THREAD

**Issue by georgemp** [m1entus/MZFormSheetController#122]
Hi,
  In the example app (Xcode5 example) and my actual app, the blurred background image seems to be incorrect after rotation to landscape view. In the example app, I am able to consistently reproduce after rotation on iPhone 6 Simulator (Device rotate right 3 times). I don't have an actual device to test on, so, am not sure if this is a simulator only issue. 
![screen shot 2014-10-07 at 7 25 46 pm](https://cloud.githubusercontent.com/assets/1289458/4543324/37d7cf0e-4e2a-11e4-814c-32bd57bc8373.png)

On my actual app, it occurs even after a single rotation on the iphone 6 simulator.
![screen shot 2014-10-07 at 7 30 41 pm](https://cloud.githubusercontent.com/assets/1289458/4543350/6a1f86d2-4e2a-11e4-9d3e-5c0fb4156c3f.png)

The code I am using is 

     BOOL legacyHardware = [RMSystemUtils legacyHardware];
    [[MZFormSheetBackgroundWindow appearance] setBackgroundBlurEffect:!legacyHardware];
    MZFormSheetController *formSheet = [[MZFormSheetController alloc] initWithViewController:navController];
    formSheet.transitionStyle = MZFormSheetTransitionStyleSlideAndBounceFromRight;
    formSheet.movementWhenKeyboardAppears = MZFormSheetWhenKeyboardAppearsMoveToTop;
    formSheet.cornerRadius = 8.0;
    CGSize formSheetSize = CGSizeZero;
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
        formSheetSize = CGSizeMake(400, 400);
    else
        formSheetSize = CGSizeMake(300, 300);
    formSheet.presentedFormSheetSize = formSheetSize; 
    [self mz_presentFormSheetController:formSheet
                               animated:YES
                      completionHandler:nil];

Any advice on tackling this would be much appreciated. Thanks

**Comment by m1entus** [comment]
I fix that issue adding shouldUseNativeBlurEffect for iOS8 which is default ON.
