### ISSUE TITLE
Layout margins aren't preserved

### ISSUE THREAD

**Issue by pronebird** [m1entus/MZFormSheetController#128]
I see that layout margins are disappeared on iOS 8 when using Form sheet.

![image](https://cloud.githubusercontent.com/assets/704044/5362268/017295e6-7fd2-11e4-95c3-d7a47abe5b0f.png)

While it is certainly there in IB:

![image](https://cloud.githubusercontent.com/assets/704044/5362271/18aa7620-7fd2-11e4-9edc-3a7a4cfed9a6.png)

Why do you think this could happen?

**Comment by sdyxch** [comment]
@pronebird  have u fixed this?

**Comment by m1entus** [comment]
I rewritten MZFormSheetController to MZFormSheetPresentationController which is build on iOS8+ and don't use UIWindow tricks. I am sure that you will not have problem if you use it

**Comment by pronebird** [comment]
@m1entus great thanks!
