### ISSUE TITLE
issues ui mzformsheet on ios 8

### ISSUE THREAD

**Issue by thetay55** [m1entus/MZFormSheetController#138]
I used mzformsheet on ios8, when i rotate ipad and show formsheet is error UI.
link screen error https://www.flickr.com/photos/129737979@N04/

**Comment by Paul75** [comment]
it is only on iPad ?

On my iPhone 5c in ios8 it good....

**Comment by thetay55** [comment]
Yes, it fail in ipad

**Comment by m1entus** [comment]
Soon i am going to work on version 2.0.0 and iOS8 will be fixed.

**Comment by m1entus** [comment]
I fix that issue adding shouldUseNativeBlurEffect for iOS8 which is default ON.

I also rewritten MZFormSheetController to MZFormSheetPresentationController which is build on iOS8+ and don't use UIWindow tricks. I am sure that you will not have problem if you use it
