### ISSUE TITLE
Problem to use in swift 

### ISSUE THREAD

**Issue by eikebartels** [m1entus/MZFormSheetController#140]
Hey,

I can't use it in swift. I get the following errors 
- "Could not build Objective-C module 'MZFormSheetController'"
- "'MZAppearance.h' file not found"

I'm using cocoa pods

Any idea?

**Comment by m1entus** [comment]
MZFormSheetController has dependency form MZAppearance https://github.com/m1entus/MZAppearance

**Comment by eikebartels** [comment]
Yea I know. The dependency is set automaticity from cocoa pod. Do I have to include it somehow?

**Comment by m1entus** [comment]
I don't know because i'm not develop using swift, in objective-c project works fine so this could be cocoapods issue with linking dependency.

**Comment by eikebartels** [comment]
Yea could be. Will try to figure it out and let you know.

**Comment by carlhunterroach** [comment]
Have you created a bridge file?

**Comment by eikebartels** [comment]
Sure!

**Comment by codeSupreme** [comment]
hey @eikebartels was you able to figure out what the solution to get this working in Swift? I am having the same issue.

**Comment by eikebartels** [comment]
Check out  #141
