### ISSUE TITLE
Pass parameters to controller

### ISSUE THREAD

**Issue by Paul75** [m1entus/MZFormSheetController#143]
Hello

I want to pass a data for the popup.

I do this :
[CODE]
formSheet.willPresentCompletionHandler = ^(UIViewController *presentedFSViewController) {
        // Passing data
        NSIndexPath *cellIndexPath = [self.tableView indexPathForCell:cell];
        
        _selectedArticle = _feedItems[cellIndexPath.row];
        
        NbArticlesPopupViewController *detailVC;
        detailVC.selectedArticle = _selectedArticle;
        
    };
[/CODE]
But nothing pass to popup do ….

the variable cell is of type : (SWTableViewCell *)cell

Thanks

**Comment by m1entus** [comment]
You're doing it wrong.... pass data to some @property object, and in viewDidLoad of presented view controller do something with this data

**Comment by Paul75** [comment]
I have a property :
@property (strong, nonatomic) Article *selectedArticle;

**Comment by Paul75** [comment]
In my code :
_selectedArticle = _feedItems[indexPath.row];
        
        NbArticlesPopupViewController *detailVC;
        detailVC.selectedArticle = _selectedArticle;

When I do 
_selectedArticle = _feedItems[indexPath.row];

I get the good item.

But when I do :
        NbArticlesPopupViewController *detailVC;
        detailVC.selectedArticle = _selectedArticle;

the detailVC.selectedArticle contain 'nil'…

Thanks

**Comment by Paul75** [comment]
Okay It works !
NbArticlesPopupViewController *sendVC = (NbArticlesPopupViewController *)presentedFSViewController;
        sendVC.selectedArticle = _selectedArticle;

But in the popup i must do it in viewDidAppear not in viewDidLoad !
