### ISSUE TITLE
Critical problem with Google-Mobile-Ads-SDK and blurred BG

### ISSUE THREAD

**Issue by marcovanetti** [m1entus/MZFormSheetController#145]
It seems that the official Google's ADV library (pod name "Google-Mobile-Ads-SDK"), from version 7.0, probably in order to optimize the performances, creates a global empty window.
When MZFormsheetController tries to create a screenshot with method 

+ (UIImage *)screenshotUsingContext:(BOOL)useContext

in MZFormSheetBackgroundWindow.m, it iterates on 

[[UIApplication sharedApplication] windows]

but when an empty window is found, the method 

[window drawViewHierarchyInRect:window.bounds afterScreenUpdates:NO];

generates a EXC_BAD_ACCESS.
The bug is reproducible only on a real device and partially documented here 

http://stackoverflow.com/questions/19903665/uigraphics-crashes-on-ios-7

A simple solution is to check if the window is empty and in the case skip it.

I added this temporary FIX to MZFormSheetBackgroundWindow.m:

if ((![window respondsToSelector:@selector(screen)] || [window screen] == [UIScreen mainScreen]) && window.tag != MZFormSheetControllerWindowTag && ![window isKindOfClass:[MZFormSheetBackgroundWindow class]])

becomes

if ((![window respondsToSelector:@selector(screen)] || [window screen] == [UIScreen mainScreen]) && window.tag != MZFormSheetControllerWindowTag && ![window isKindOfClass:[MZFormSheetBackgroundWindow class]] && window.bounds.size.width > 0 && window.bounds.size.height > 0)

Bye,
Marco

**Comment by m1entus** [comment]
Thanks
