### ISSUE TITLE
The "MZFormSheetControllerExample" not launch errors

### ISSUE THREAD

**Issue by Paul75** [m1entus/MZFormSheetController#147]
Hello,

I want to test the program example "MZFormSheetControllerExample" and it not want to launch :
The messages :
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MZFormSheetBackgroundWindowViewController", referenced from:
      objc-class-ref in MZFormSheetController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

thanks

**Comment by m1entus** [comment]
User this Xcode5 iOS 7 Example/Xcode5Example , MZFormSheetControllerExample is old and will be deleted soon.

**Comment by Paul75** [comment]
Thanks a lot.

Very good job :)

Dziękuję bardzo za waszą pracę.
