### ISSUE TITLE
Presentation Controller Corner Radius Support

### ISSUE THREAD

**Issue by ay8s** [m1entus/MZFormSheetController#152]
Noticed that the corner radius within the new Presentation Controller doesn't seem to be customisable. Could that be an additional option? 

Loving the new Presentation Controller by the way! So much nicer without the hacks! :+1:

**Comment by m1entus** [comment]
Did you try to set masksToBounds and after that cornerRadius to container, shound work. Thanks :)

**Comment by ay8s** [comment]
Doesn't look like MZFormSheetPresentationController reveals a container? Might be missing the trick here. I tried setting those on the view I am presenting but didn't have any effect. 

I think the tweak required is changing https://github.com/m1entus/MZFormSheetController/blob/master/MZFormSheetController/MZFormSheetPresentationController/MZFormSheetPresentationController.m#L276 to be dynamic.

**Comment by m1entus** [comment]
Sound like it could fix it, did you tried to delete this line and set corner radius, or set it on viewWillAppear?

**Comment by ay8s** [comment]
I didn't however I did tweak the radius on this line and it did change the modal correctly. A method for doing that would be great, can see a few other people wanting to do similar.

Top work on this! :)

**Comment by m1entus** [comment]
Thanks, i just deleted curnerRadius from setup, now you can manipulate it before presenting view controller
