### ISSUE TITLE
The "s.platform" in podspec

### ISSUE THREAD

**Issue by thinkwing** [m1entus/MZFormSheetController#155]
I found the "s.platform" in podspec was 6.1, what about other platform?  Such as 6.0, 5.x and so on.
Any idea?

**Comment by m1entus** [comment]
This is because SVProgressHUD, if you want to use in older version such a 5.x just download source and include without cocoapods, or download older version in pods

**Comment by thinkwing** [comment]
Many thanks!!!   I don't use SVProgressHUD, however, in order to deploy my project to IOS platform 6.0, can I use the newest version in pods, like "  pod 'MZFormSheetController', '~> 3.0.2'  " ???

**Comment by m1entus** [comment]
No you can't but version 3.0 introduced new way presenting popup which is supported only by ios8, nothing changed

**Comment by thinkwing** [comment]
To support IOS6.0, I use " if ..... else...... " to solve problems between ios8 and other version, running normally! May I use MZFormSheetController like this below?
![57fe508a-23b0-4bdf-8399-0724a9de9bff](https://cloud.githubusercontent.com/assets/368345/6652944/12a76628-cabb-11e4-9f48-2fd348bc12cf.png)
![57fe508a-23b0-4bdf-8399-0724a9de9bff](https://cloud.githubusercontent.com/assets/368345/6652945/1c2408b4-cabb-11e4-87e4-051ae1b0bd41.png)

**Comment by thinkwing** [comment]
I just only use MZFormSheetPresentationController on ios8, and other version such as 6.0, 6.1 and so, I use MZFormSheetController

**Comment by m1entus** [comment]
Yes you can use it in that way, dependency is 6.1 because pod didn't allow me to set lower because SVProgressHUD, but it will work on iOS 5.x

**Comment by thinkwing** [comment]
I see, many many many thanks! By the way, if spliting this pod into two pods, one is "MZFormSheetController", and the other one is "MZFormSheetController+SVProgressHUD", the first one is to be set lower ......
