### ISSUE TITLE
Can't use the library 

### ISSUE THREAD

**Issue by Morisi** [m1entus/MZFormSheetController#158]
when i added the library to the project its gives me error about - NSString not found and also for NSObject also , etc..

i found out the the foundation library was missing and i've added it but yet it doesn't solve my problem...

**Comment by m1entus** [comment]
https://github.com/m1entus/MZFormSheetController/issues/131

**Comment by Morisi** [comment]
i've added import  (for uikit ) in any file of the library and also import foundation at the problematic file
