### ISSUE TITLE
Feature: Support different movement actions when keyboard appears depending on fits view or not.

### ISSUE THREAD

**Issue by iThinker** [m1entus/MZFormSheetController#161]
I have viewController with a bunch of textFields. They have different inputViews with different height.
And it would be nice to have ability to specify different behavior for different cases.
In my case I want view to be centered if it fits on screen and be attached to top otherwise.
It's like "take as much place as you can and truncate top (bottom) otherwise".

**Comment by m1entus** [comment]
Just set keyboardAppearence to do nothing are set malualy presentedFSFrame

**Comment by iThinker** [comment]
From where to set it?
ViewController is not aware how it is presented.

**Comment by m1entus** [comment]
Supported in new https://github.com/m1entus/MZFormSheetPresentationController , you can add your custom view controller movement style.
