### ISSUE TITLE
Upgrading from MZFormSheetController to MZFormSheetPresentationController

### ISSUE THREAD

**Issue by eliburke** [m1entus/MZFormSheetController#162]
Michał,
I'm trying to upgrade my app to use your new PresentationController class, and having a rough time of it. I don't know if I'm missing something obvious, or if I was using the FormSheetController in a way that is just making this hard to convert. 

Example: I have a number of ViewControllers with a class method like this:
```
+ (void) showModal {
    MyViewController * vc = [[MyViewController alloc] init];
    MZFormSheetController *formSheet = [[MZFormSheetController alloc] initWithViewController:vc];
    [formSheet presentAnimated:YES completionHandler:nil];
}
```

Inside those classes, there are sometimes buttons to dismiss or load another view controller:
```
[self mz_dismissFormSheetControllerAnimated:YES completionHandler:nil];
    or
[self.formSheetController presentViewController:activityVC animated:YES completion:nil];
```

I've switched all the necessary properties from FormSheetController to PresentationController, but how do I present and dismiss using the new class? It seems like there is no longer a shared queue; am I now on the hook to do more management from the parent view controller?

Thanks
Eli

**Comment by m1entus** [comment]
New presenting view controller work as na reguler view controller, so to present just use presentViewController:animated , there is no shared queue, it works as a regular modal controller

**Comment by eliburke** [comment]
There seems to be a pretty dramatic difference between standard modal views and the old MZFormSheetController class: a ViewController can only present one other ViewController. 

I have been using MZFormSheetController for, among other things, stateless popups that sometimes appear over each other (a UIAlertView replacement that is triggered by asynchronous events). This is no longer possible: once one alert is shown, additional alerts trigger this error: "Warning: Attempt to present <MZFormSheetPresentationController: 0xf57fa00>  on <MZFormSheetPresentationController: 0xf713760> which is already presenting". It seems as though I will have to either revert, or recreate the viewController stack from the previous version.

I understand your desire to use the Apple standard design, but I think your documentation on the new PresentationController should make this limitation more clear. Maybe you should even split it off into a separate repository.

**Comment by m1entus** [comment]
I didn't split it in two repositeries because i will not be longer support MZFormSheetController, it is buggy and breaks Apple guildelines. If you have error "Warning: Attempt to present on which is already presenting", you are doing something wrong, you can always present new view cotnroller from one which is at the top.

**Comment by eliburke** [comment]
I think I've finally converted everything over and chased down all the bugs. This bit of code may be useful to people in my situation (asynchronous MZFormSheetPresentationControllers). When you create a new formsheet and present it, use the view controller returned by this method  to present new formsheets.

    + (UIViewController*) topMostController {
        UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
        while (topController.presentedViewController) {
            topController = topController.presentedViewController;
        }  
        return topController;
    }
