### ISSUE TITLE
MZAppearance not accessible from swift

### ISSUE THREAD

**Issue by Arrnas** [m1entus/MZFormSheetController#164]
looks like it's not possible to modify the appearance via `MZFormSheetBackgroundWindow.appearance()` in swift. The return value of `.appearance()` is cast  to AnyObject and casting it to `MZFormSheetBackgroundWindow` or `MZAppearance` or even `NSProxy` doesn't work
>Could not cast value of type 'MZAppearance' (0x110125118) to 'MZAppearance' (0x110125118).

the only explanation I can find is: 
>In ObjC this is usually implemented as a proxy object which handles value
>	access transparently, but Swift doesn't have proxy objects and can't subclass
>	NSProxy either - all ObjC objects passed to Swift have to subclass NSObject.

from: https://github.com/rbrockerhoff/SwiftChecker/blob/master/SwiftChecker/Future.swift

**Comment by m1entus** [comment]
Yes, all i need to do is change inheritance from NSProxy to NSObject. When i will find some time i will do it.

**Comment by m1entus** [comment]
Fixed.

**Comment by Arrnas** [comment]
thanks a lot @m1entus!

**Comment by Arrnas** [comment]
it still wouldn't work so I changed the return types from `id` to `instancetype` and `MZFormSheetBackgroundWindow.appearance().backgroundBlurEffect = true` works now

**Comment by m1entus** [comment]
Ok thanks, i fixed it and updated pods.
