### ISSUE TITLE
Data Passing not working?

### ISSUE THREAD

**Issue by pranjalsatija** [m1entus/MZFormSheetController#165]
I'm using MZFormSheetController to pass data from one text field to a form sheet. I'm using the following code:

```Swift
let presentationController = MZFormSheetPresentationController(contentViewController:viewToPresent);

//does some stuff

presentationController.willPresentContentViewControllerHandler = {(presented) in
     let justPresented = presented as! SearchResultsWindowController;
     justPresented.userNameToSearch = self.searchField.text;
}
```

SearchResultsWindowController is my destination view controller, and searchField is a UITextField that the user enters their search into. My destination view controller is not receiving the string I'm attempting to pass.

**Comment by m1entus** [comment]
It works: https://github.com/m1entus/MZFormSheetController/blob/master/Example/Xcode5%20iOS%207%20Example/Xcode5Example/Xcode5Example/MZPresentationViewController.m#L60
