### ISSUE TITLE
Warning - Incompatible pointer types returning 'MZAppearancance

### ISSUE THREAD

**Issue by Jules2010** [m1entus/MZFormSheetController#168]
/Users/jm/Dropbox/Code_ObjC/BalanceGuide/Pods/MZFormSheetController/MZFormSheetController/MZFormSheetBackgroundWindow.m:93:12: Incompatible pointer types returning 'MZAppearance *' from a function with result type 'MZFormSheetBackgroundWindow *'

Hey I'm getting this warning, i'm running xcode 6.3.2, the pod update forced version 3.0.3 where I was using 3.0 without a warning.

**Comment by m1entus** [comment]
I Fixed MZAppearance, should work fine.

**Comment by Jules2010** [comment]
Hi,

Has that been committed ?

Thanks,

Jules.

**Comment by m1entus** [comment]
Yes, pod update

**Comment by Jules2010** [comment]
Ah ok, awesome, I thought there would be a new version number, thanks.
