### ISSUE TITLE
MZFormSheetPresentationController always square

### ISSUE THREAD

**Issue by mbcoder17** [m1entus/MZFormSheetController#169]
I am using MZFormSheetPresentationController in my app, but every time I display the controller, it always takes the view controller from the storyboard and scales it down and displays it as a square. Is there anyway I can change the frame of the presented view. 

In my screenshot below, for example, what if I want the button to be at the top of the view, and I want the height of the form sheet to be the height of the button so there is not a lot of space below it?

![ios simulator screen shot may 19 2015 11 34 18 am](https://cloud.githubusercontent.com/assets/4973557/7706901/06ed3cac-fe1b-11e4-9154-89b6c3a0ab16.png)

**Comment by m1entus** [comment]
@property (nonatomic, assign) CGSize contentViewSize MZ_APPEARANCE_SELECTOR;

**Comment by mbcoder17** [comment]
Sorry, I didn't see that. Works like a charm!
