### ISSUE TITLE
why does error occurs in MZTransition.h?

### ISSUE THREAD

**Issue by leizh007** [m1entus/MZFormSheetController#170]
I inherit the LZHCustomeTransition : MZTransition. and set [MZFormSheetController registerTransitionClass:[LZHCustomeTransition class] forTransitionStyle:MZFormSheetTransitionStyleCustom];

but when I run the program it tells me that - (void)entryFormSheetControllerTransition:(UIViewController *)formSheetController completionHandler:(MZTransitionCompletionHandler)completionHandler;

the UIViewController expected a type.? How did that comming?

http://stackoverflow.com/questions/30365086/error-occurs-when-using-cocoapods

**Comment by m1entus** [comment]
You are missing UIKit framework import. You have to @import UIKit;
