### ISSUE TITLE
Redraw popup content after keyboard show/hide

### ISSUE THREAD

**Issue by CrazyKoala** [m1entus/MZFormSheetController#171]
Hi.
Is there a way to have the stack of viewcontrollers to be redrawn upon showing/hiding the keyboard ?

I am shrinking the frame of the popup upon keyboard showing, and it's working.
But when I restore the frame to the original frame, when the keyboard disappears, the view remains small (Despite the frame being correct). Then if I rotate the device, the view is properly rendered.

**Comment by m1entus** [comment]
It is hard to say, MZFormSheetController is presented on own window maybe you could try setNeedsDisplay on it? As i said i previous issues use MZFormSheetPresentationController if you can, it is bug free

**Comment by CrazyKoala** [comment]
I worked around this issue by using viewwillappear in my shown VC to restore proper frame upon rotation when the popup is displayed.

Somehow setneeddisplay didn't work.
