### ISSUE TITLE
Cannot assign Blue effect with swift

### ISSUE THREAD

**Issue by 1412** [m1entus/MZFormSheetController#173]
i want to convert this line

[[MZFormSheetBackgroundWindow appearance] setBackgroundBlurEffect:YES];
[[MZFormSheetBackgroundWindow appearance] setBlurRadius:5.0];
[[MZFormSheetBackgroundWindow appearance] setBackgroundColor:[UIColor clearColor]];

to

MZFormSheetBackgroundWindow.appearance().setBackgroundBlurEffect();

but i got

'AnyObject' does not have a member named 'setBackgroundBlurEffect()'

**Comment by m1entus** [comment]
MZFormSheetPresentationController was rewritten and build on iOS 8 API. You can still use MZFormSheetController if you want to support iOS5 >, but if you have deployment target set to iOS8 i recommed you to use MZFormSheetPresentationController. It don't use any tricky hacks to present form sheet as a UIWindow, it use native modalPresentationStyle UIModalPresentationOverFullScreen.
