### ISSUE TITLE
Unclear "Read Me"

### ISSUE THREAD

**Issue by walsh2000** [m1entus/MZFormSheetController#179]
May I suggest that you change your read me from:

> You can still use MZFormSheetController if you want to support iOS5 >, 

To:

> You can still use MZFormSheetController if you want to support <iOS8

If you have an app that supports iOS8 & iOS7, MZFormSheetPresentationController is not an option. Your read me seems to indicate that you want MZFormSheetController only if you're supporting iOSes below 5, but even iOS7 as a requirement means you need to use MZFormSheetController.

**Comment by m1entus** [comment]
Thanks, done.
