### ISSUE TITLE
Cocoapods Installation Issue

### ISSUE THREAD

**Issue by ay8s** [m1entus/MZFormSheetController#180]
Not sure if this is happening to anyone else with 3.1.0 but I keep getting this error with Cocoapods 0.37 and 0.38 beta... 

![screen shot 2015-07-06 at 12 25 15](https://cloud.githubusercontent.com/assets/1058408/8531152/3d48a69e-23da-11e5-9acf-b7965bfd44d2.png)

**Comment by m1entus** [comment]
Did you try to setup again cocoapods master repository using pod setup ?

**Comment by ay8s** [comment]
If I add the dependency to my podspec file as ":git => 'https://github.com/m1entus/MZFormSheetController.git'" it works. 3.1.0 didn't seem to work.

Will run that now @m1entus

**Comment by ay8s** [comment]
Apologies @m1entus. Think I was a little hasty with the GitHub issue. Will close this unless it comes up again.
