### ISSUE TITLE
Wrong background on iOS9

### ISSUE THREAD

**Issue by IntellectSoftDeveloper** [m1entus/MZFormSheetController#183]
Transparent background does not cover full screen on iOS9.
It seems the following condition from MZFormSheetController.m doesn't work correctly:

```
        if (MZSystemVersionGreaterThanOrEqualTo_iOS8() && UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation)) {
```

**Comment by ab-rdarts** [comment]
I think it's related to iOS8.4 problem also. The workaround is to remove above condition and setup at least empty UIViewController for iOS8 and higher.
