### ISSUE TITLE
Pass touches through a part of the screen

### ISSUE THREAD

**Issue by Skornos** [m1entus/MZFormSheetController#187]
Hi,

I love your library, saves me a lot of time. Right now I am trying to solve this: is it possible to create  MZFormSheetController instance where part of the screen is transparent (let's say a rectangle in the middle of the screen where alpha is set to 0.0) and the controller passes touches to the view controller underneath.

Or would it be possible with MZFormSheetPresentationController? 

Thanks.

**Comment by m1entus** [comment]
Yes, chceck transparentTouchesEnabled property

**Comment by Skornos** [comment]
Thanks for the fast response! :+1: 

I am setting presentedFormSheetSize to be equal to the underlying view controller's size and also I am setting transparentTouchEnabled to YES but I can tap only on the navigation or tab bar. The touches on the MZFormSheetController are passed underneath.

**Comment by Skornos** [comment]
To be more specific, I attach this example:

The orange tooltip on the bottom is what I am presenting on my instance of MZFormSheetController. In addition to it I would love to have the red rectangle transparent and be able to pass the taps to it (it displayes collection of views). Appreciate your help :)

![Example](http://s7.postimg.org/nnc96zfij/mzformsheet.png)

**Comment by m1entus** [comment]
Hard to say what is going on here, but you could you Reveal to check what is going on, or prepare some short example for me, because transparentTouchesEnabled should make job done here.

**Comment by Skornos** [comment]
I am initializing the MZFormSheetController like this:

    BFNCheckoutTooltipViewController *tooltipVC = [[BFNCheckoutTooltipViewController alloc] init];
    [[MZFormSheetController sharedBackgroundWindow] setBackgroundColor:[UIColor colorWithRed:0 green:0 blue:0 alpha:0.3]];
    MZFormSheetController *formSheet = [[MZFormSheetController alloc] initWithViewController:tooltipVC];
    formSheet.shouldCenterVertically = YES;
    formSheet.formSheetWindow.transparentTouchEnabled = YES;
    formSheet.transitionStyle = MZFormSheetTransitionStyleSlideFromBottom;
    formSheet.presentedFormSheetSize = tableViewController.view.frame.size;
    formSheet.willDismissCompletionHandler = ^(UIViewController *viewController) {
        [UIView animateWithDuration:0.3
                              delay:0
                            options:UIViewAnimationOptionBeginFromCurrentState
                         animations:^{
                             tableViewController.tableView.contentInset = UIEdgeInsetsZero;
                             tableViewController.tableView.scrollIndicatorInsets = UIEdgeInsetsZero;
                         }
                         completion:nil];
    };
    formSheet.didPresentCompletionHandler = ^(UIViewController *viewController) {
         if (tableViewController.tableView.contentSize.height > tableViewController.tableView.frame.size.height)
         {
             CGPoint offset = CGPointMake(0, tableViewController.tableView.contentSize.height - tableViewController.tableView.frame.size.height + 100);
             [tableViewController.tableView setContentOffset:offset animated:YES];
             tableViewController.tableView.contentInset = UIEdgeInsetsMake(0, 0, 100, 0);
             tableViewController.tableView.scrollIndicatorInsets = UIEdgeInsetsMake(0, 0, 100, 0);
         }
        
    };
    [tableViewController mz_presentFormSheetController:formSheet animated:YES completionHandler:nil];

`BFNCheckoutTooltipViewController` contains single UIView subclass (the orange tooltip) which is aligned to the bottom of the view with Auto Layout. 

Isn't the problem there that my `formSheet.presentedFormSheetSize` is set to `tableViewController.view.frame.size` and the touches doesn't get passed through the view?

![Capture of the screen](http://s7.postimg.org/je3eag3t7/Sni_mek_obrazovky_2015_10_12_v_21_03_16.png)

**Comment by m1entus** [comment]
Probably it is a problem that formSheet.presentedFormSheetSize is set to tableViewController.view.frame.size, because it allows to touch area around it.

**Comment by Skornos** [comment]
I suppose that setting transparentTouchEnabled property to YES enables taps outside of the area of my formSheetWindow. So if I set the window to be as big as my view controller than I am not getting any taps on it or am I missing something about this property? 

To make sure I have set the presentedFormSheetSize to CGSizeMake(200, 200) and I was able to tap on anything outside of this 200x200 area but not inside of it. So back to my original question would it be possible to bypass these touches even inside the formSheetWindow area? 

BTW: greetings to Cracow from Ostrava, Czech republic

**Comment by m1entus** [comment]
You should receive touches also inside of it, please prepare some example, if you will make it, for sure i will help you with it ;)

**Comment by Skornos** [comment]
Thanks. I have created a minimal example in here using cocoapods

https://github.com/Skornos/TooltipTest

If you tap outside the red rectangle you should see "tapped" in logs, if you tap inside the rectangle there is not action logged.

**Comment by Skornos** [comment]
I have tested it further. If you always return `NO` from `MZFormSheetController:pointInside:withEvent` it gets the job done so I would look for clues there. Anyway my custom button inside orange tooltip is ignored. 

I have updated the example project. Now there is a green button inside the red rectangle. The expected behaviour is folllowing: if you tap the green button, you'll see "tapped button" in logs. If you tap red rectangle outside the button or the dimmed background view there will be "tapped outside" in logs. Is it possible?

**Comment by m1entus** [comment]
Your example works fine for me, if i tap green button i see tapped button, and if i tap outside i see tapped outside, i have tested on iOS8 and iOS9, Xcode 7

![zrzut ekranu 2015-10-13 o 10 34 10](https://cloud.githubusercontent.com/assets/1565368/10449772/fba2a726-7195-11e5-96b9-e8923a97f90e.png)

**Comment by Skornos** [comment]
Do you see *tapped outside* even if you tap on the **red rectangle**?

**Comment by m1entus** [comment]
To be able to red rentable to be transparent you will have to subclass from MZFormSheetController and use '- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event' to handle transparency for your green rect.
