### ISSUE TITLE
portraitTopInset on device rotation

### ISSUE THREAD

**Issue by hebbian** [m1entus/MZFormSheetController#188]
Thanks for awesome library.
I ran the example that comes with your files, and I found that I can't set the portraitTopInset after device rotation from landscape to portrait view.
First, everything goes ok in portrait mode : 
![screen shot 2015-10-13 at 14 26 33](https://cloud.githubusercontent.com/assets/2240177/10449634/0e53b42c-71bf-11e5-8d9d-72e1510ae67d.png)

Also, in landscape mode, it's ok : 
![screen shot 2015-10-13 at 14 26 41](https://cloud.githubusercontent.com/assets/2240177/10449641/1928a83a-71bf-11e5-8033-6cec701c706a.png)

But, when I rotate the device again to portrait mode, this is what I found:
![screen shot 2015-10-13 at 14 26 57](https://cloud.githubusercontent.com/assets/2240177/10449646/21f40ae0-71bf-11e5-84d1-9856b91fd9bb.png)

It looks like, portraitTopInset is not applied to the third screen (portrait mode), what's going on?

**Comment by hebbian** [comment]
No one?

**Comment by m1entus** [comment]
Already fixed in: https://github.com/m1entus/MZFormSheetPresentationController
