### ISSUE TITLE
In-Call or Hotspot Activated statusbar height

### ISSUE THREAD

**Issue by ericertl** [m1entus/MZFormSheetController#195]
Hi @m1entus  . I'm not sure if you're still supporting this control, but I hope you are.
I'm experiencing a problem when the statusbar height changes its size for an incoming call or when the hotspot is activated pushing the views down instead of resizing them.
You can reproduce this with the simulator using **cmd + Y** to simulate an incoming call in the demo apps.

I'm presenting a view which uses the whole screen size, and when the statusbar changes things get shifted down instead of resizing and I have UI elements moved partially off screen.

Changing:
````
formSheet.presentedFormSheetSize = [UIScreen mainScreen].bounds.size;
````
in MZViewController.m in the demo will show what I'm talking about.

I tried resizing my viewcontroller using **UIApplicationWillChangeStatusBarFrameNotification** and **UIApplicationDidChangeStatusBarFrameNotification** but it doesn't work.

**Comment by m1entus** [comment]
You would have to change presentedFSViewController.view frame istead of presentedFormSheetSize.

**Comment by ericertl** [comment]
Thanks @m1entus. It's working now. I saw you implemented **UIApplicationDidChangeStatusBarFrameNotification** in MZFormSheetBackgroundWindow. I tried to use its **didChangeStatusBarFrame** delegate to change the presentedFSViewController frame in just one place but couldn't access presentedFSViewController from the delegate, so I ended up the notifications on the viewcontrollers
