### ISSUE TITLE
Lots of memory leaks

### ISSUE THREAD

**Issue by ratzr15** [m1entus/MZFormSheetController#196]
- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector
{
    return [self.mainClass instanceMethodSignatureForSelector:aSelector];
}

Checking with instruments, my app was
<img width="1018" alt="screen shot 2016-04-18 at 10 27 51 am" src="https://cloud.githubusercontent.com/assets/3498597/14595465/88e6c7a4-0550-11e6-84dd-aa6b988324f4.png">
 consuming more memory than expected. Later found most of them to be from the above method.

**Comment by m1entus** [comment]
This is how UIAppearance proxy works, not memory leak, because all data need to be in memory to be able to apply invocation to objects when they are needed
