### ISSUE TITLE
How  can i change the ViewController`s frame.

### ISSUE THREAD

**Issue by ZT0526** [m1entus/MZFormSheetController#198]
if i want to use UITextView in the ViewController  , how  can i change the ViewController`s frame dynamically?

**Comment by m1entus** [comment]
You have to use this: https://github.com/m1entus/MZFormSheetPresentationController

**Comment by ZT0526** [comment]
Thank You . I've already seen this. But I found that this is in excessive animation can modify the frame. And I want to change the frame after the animation .When I enter text , ViewController`s frame also follow changes.Can you give me a guide？My great god
